[package]
name = "blog"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
html-escape = "0.2"
pulldown-cmark = "0.10"
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4", default-features = false, features = ["alloc", "std"] }
