[build]
builder = "DOCKERFILE"
watchPatterns = ["src/**", "posts/**", "assets/**", "Cargo.toml", "Cargo.lock", "Dockerfile"]

[deploy]
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/healthz"
healthcheckTimeout = 60
